### ISSUE TITLE
Error while running setup.py

### ISSUE THREAD

**Issue by Ryankim28** [hujiecpp/YOSO#17]
HI
Error while running setup.py
```
Traceback (most recent call last):
  File "setup.py", line 156, in get_model_zoo_configs
    os.symlink(source_configs_dir, destination)
FileExistsError: [Errno 17] File exists: '/YOSO/configs' -> '/YOSO/detectron2/model_zoo/configs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 173, in <module>
    package_data={"detectron2.model_zoo": get_model_zoo_configs()},
  File "setup.py", line 159, in get_model_zoo_configs
    shutil.copytree(source_configs_dir, destination)
  File "/opt/conda/envs/YOSO/lib/python3.8/shutil.py", line 555, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/YOSO/configs'
```
I try the seting but it is error

**Comment by Leoric1** [comment]
As indicated in the tip, deleting the configs file in the '/YOSO/detectron2/model_zoo/configs' path can resolve this issue.
